# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a35tcpg236-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/NWang/OneDrive/Others/Documents/GitHub/cpe233/rat3/rat3.cache/wt [current_project]
set_property parent.project_path C:/Users/NWang/OneDrive/Others/Documents/GitHub/cpe233/rat3/rat3.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
read_vhdl -library xil_defaultlib C:/Users/NWang/OneDrive/Others/Documents/GitHub/cpe233/rat3/rat3.srcs/sources_1/new/register_file.vhd
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top REG_FILE -part xc7a35tcpg236-1


write_checkpoint -force -noxdef REG_FILE.dcp

catch { report_utilization -file REG_FILE_utilization_synth.rpt -pb REG_FILE_utilization_synth.pb }
